### ISSUE TITLE
config file is not in backpack folder

### ISSUE THREAD

**Issue by tabacitu** [jsiebach/commander#2]
All other Backpack packages publish their files inside the ```config/backpack``` folder, but Commander publishes it in ```config/commander.php```. I suggest we publish this one in the backpack folder too, for consistency?

This is a minor change, of course. I'm just mentioning this now because it's a breaking change, and it's probably a good idea to do this before people start flooding in to use the package.

Great work - again. Cheers!

**Comment by jsiebach** [comment]
I pushed an update for this.  Good catch.  I also re wrote my service provider a bit after reading through the Backpack/Base one, I like the folder structure now better.

I am new to maintaining packages so I will try to keep from any breaking changes, will be a bit of an adventure here.  Once I investigate a couple more of the ideas I'd like to implement I will work to get to a stable version.

Thanks for the pull request and the feedback, I definitely scrambled the docs together last night after finally publishing the package and agree the images are important.  I will continue to update them.

Thanks for offering to put this in the newsletter, very cool!

**Comment by tabacitu** [comment]
No problem, you're not alone in this, if you need help with anything feel free to mention me here or email me at hello@tabacitu.ro 

I've thrown myself into maintaining a bunch of packages 2 years ago with zero prior knowledge. So I know it can be overwhelming at times. It's usually not the technical factor that's difficult, but the human one :-) But overall I promise it's very rewarding. It's so great to know thousands of people _just like you_ are enjoying your work.

Good luck. Let's do this! :-)
