### ISSUE TITLE
suggestion: create releases with tags

### ISSUE THREAD

**Issue by eduardoarandah** [jsiebach/commander#3]
Hi!

Let me suggest you create a "release" to let users install simply with 

`composer require jsiebach/commander`

Just to go "releases" "draft a new release" and tag it with something like 1.0.1

![imagen](https://user-images.githubusercontent.com/4065733/34360227-4563069a-ea24-11e7-8461-9a4e8b5a59c3.png)

![imagen](https://user-images.githubusercontent.com/4065733/34360238-57cc38e2-ea24-11e7-9e38-faff3be2fbea.png)

Do that with every functional commit to let users upgrade easily

**Comment by jsiebach** [comment]
Thank you for the tip, I was waiting to publish it to get some feedback.  I've made a couple of edits since then and I went ahead and published 1.0!
