### ISSUE TITLE
About update

### ISSUE THREAD

**Issue by felipetmartini** [jsiebach/commander#4]
This will be updated to crud 3.4????

c:\xampp\htdocs\EquipeAtuarial>composer require jsiebach/commander
Using version dev-master for jsiebach/commander
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: backpack/crud[3.2.x-dev, 3.4.17].
    - Can only install one of: backpack/crud[3.4.17, 3.2.x-dev].
    - Can only install one of: backpack/crud[3.2.x-dev, 3.4.17].
    - jsiebach/commander dev-master requires backpack/crud 3.3.*|3.2.* -> satisfiable by backpack/crud[3.2.x-dev].
    - Installation request for jsiebach/commander dev-master -> satisfiable by jsiebach/commander[dev-master].
    - Installation request for backpack/crud (locked at 3.4.17, required as ^3.4) -> satisfiable by backpack/crud[3.4.17].

Installation failed, reverting ./composer.json to its original content.

**Comment by jsiebach** [comment]
Fixed, thanks for the note!
