### ISSUE TITLE
A question, sorry but im new with that

### ISSUE THREAD

**Issue by felipetmartini** [jsiebach/commander#5]
i have this in mysql and when try to see the comands not shw nothing, say a error

Undefined index: dump (View: C:\xampp\htdocs\EquipeAtuarial\vendor\backpack\crud\src\resources\views\columns\model_function.blade.php) {"userId":1,"email":"felipemartini@brturbo.com.br","exception":"[object] (ErrorException(code: 0): Undefined index: dump (View: C:\\xampp\\htdocs\\EquipeAtuarial\\vendor\\backpack\\crud\\src\ esources\\views\\columns\\model_function.blade.php) at C:\\xampp\\htdocs\\EquipeAtuarial\\vendor\\jsiebach\\commander\\src\\CommanderCommand.php:62, ErrorException(code: 0): Undefined index: dump at C:\\xampp\\htdocs\\EquipeAtuarial\\vendor\\jsiebach\\commander\\src\\CommanderCommand.php:62)

what more i have to do to run a composer dump??

	
id
descriptive_name
command
created_at
updated_at

1
Composer Dump
dump
2018-07-01 00:57:19
2018-07-01 00:57:19

**Comment by jsiebach** [comment]
This package only runs artisan commands.  So the `command` field should be something that would fit after `php artisan`, like `migrate` or `queue:work` or something like that.
